-include device/semc/msm7x27-common/BoardConfigCommon.mk
-include vendor/semc/shakira/BoardConfigVendor.mk

TARGET_BOOTLOADER_BOARD_NAME := shakira
TARGET_OTA_ASSERT_DEVICE := E15i,E15a,E16i,E16a,shakira
PRODUCT_BUILD_PROP_OVERRIDES += TARGET_BOOTLOADER_BOARD_NAME=shakira
BOARD_CAMERA_NO_AUTOFOCUS := true
BOARD_LIBSENSORS_AKM8975 := true

TARGET_ARCH := arm
TARGET_BOARD_PLATFORM := msm7x27
TARGET_ARCH_VARIANT := armv6-vfp
TARGET_CPU_ABI := armeabi-v6l
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := generic
TARGET_BOARD_PLATFORM_GPU := qcom-adreno200
BOARD_AVOID_DRAW_TEXTURE_EXTENSION := true

